#!/usr/bin/env bash
set -euo pipefail

# generate_skill_from_mcp.sh
#
# Helper script that invokes mcporter to generate a CLI from an MCP server
# and packages the generated CLI into a new assistant skill under .pi/skills.
#
# Usage:
#   ./generate_skill_from_mcp.sh --command "<mcp command>" --bundle "<bundleName>" --skill-name "<skillName>" [--output-dir "<path>"] [--force]

show_usage() {
  cat <<EOF
Usage: $0 --command "<mcp command>" --bundle "<bundleName>" --skill-name "<skillName>" [--output-dir "<path>"] [--force]

Example:
  $0 --command "https://mcp.context7.com/mcp" --bundle "context7-cli" --skill-name "context7" --force

This script requires 'npx' to be available in PATH and will call:
  npx mcporter generate-cli --command "<mcp command>" --bundle "<bundleName>"

Notes:
- Do not include secrets (API keys, passwords) in the --command argument.
- The generated skill is created under .pi/skills/<skill-name> by default.
EOF
}

if [ "$#" -eq 0 ]; then
  show_usage
  exit 1
fi

# Argument parsing
MCP_COMMAND=""
BUNDLE=""
SKILL_NAME=""
OUTPUT_DIR=""
FORCE=0

while [ "$#" -gt 0 ]; do
  case "$1" in
    --command)
      MCP_COMMAND="$2"; shift 2;;
    --bundle)
      BUNDLE="$2"; shift 2;;
    --skill-name)
      SKILL_NAME="$2"; shift 2;;
    --output-dir)
      OUTPUT_DIR="$2"; shift 2;;
    --force)
      FORCE=1; shift 1;;
    -h|--help)
      show_usage; exit 0;;
    *)
      echo "Unknown argument: $1" >&2; show_usage; exit 2;;
  esac
done

if [ -z "$MCP_COMMAND" ] || [ -z "$BUNDLE" ] || [ -z "$SKILL_NAME" ]; then
  echo "Error: --command, --bundle and --skill-name are required." >&2
  show_usage
  exit 2
fi

# Ensure npx is available
if ! command -v npx >/dev/null 2>&1; then
  echo "Error: npx is not available in PATH. Please install Node.js and ensure npx is available." >&2
  exit 3
fi

# Resolve destination directory
if [ -z "$OUTPUT_DIR" ]; then
  DEST_DIR=".pi/skills/$SKILL_NAME"
else
  DEST_DIR="$OUTPUT_DIR"
fi

# Prevent accidental overwrite
if [ -d "$DEST_DIR" ] && [ "$FORCE" -ne 1 ]; then
  echo "Error: destination directory '$DEST_DIR' already exists. Use --force to overwrite." >&2
  exit 4
fi

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

echo "[create-skill-from-mcp-server] Temporary working directory: $TMPDIR"
cd "$TMPDIR"

# Run mcporter to generate the CLI bundle
echo "[create-skill-from-mcp-server] Running: npx mcporter generate-cli --command '$MCP_COMMAND' --bundle '$BUNDLE'"
set +e
npx --yes mcporter generate-cli --command "$MCP_COMMAND" --bundle "$BUNDLE"
MC_RET=$?
set -e
if [ $MC_RET -ne 0 ]; then
  echo "Error: mcporter failed with exit code $MC_RET" >&2
  exit $MC_RET
fi

# Locate generated artifact. mcporter typically writes an executable file named as the bundle.
GENERATED=""
if [ -f "$TMPDIR/$BUNDLE" ]; then
  GENERATED="$TMPDIR/$BUNDLE"
else
  # try to find a file whose name starts with the bundle name
  GENERATED=$(find "$TMPDIR" -maxdepth 1 -type f -name "$BUNDLE*" -print -quit || true)
fi

if [ -z "$GENERATED" ]; then
  # as a fallback, pick a non-empty file in the tmp dir
  GENERATED=$(find "$TMPDIR" -maxdepth 1 -type f -size +0c -print -quit || true)
fi

if [ -z "$GENERATED" ]; then
  echo "Error: could not find generated CLI artifact in $TMPDIR" >&2
  exit 5
fi

echo "[create-skill-from-mcp-server] Found generated artifact: $GENERATED"

# Prepare destination
rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"

BASENAME=$(basename "$GENERATED")
DEST_FILE="$DEST_DIR/$BASENAME"

mv "$GENERATED" "$DEST_FILE"
chmod +x "$DEST_FILE"

# Create a minimal SKILL.md placeholder and metadata for the assistant to populate
CREATED_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
cat > "$DEST_DIR/SKILL.md" <<SKILL_MD
---
name: $SKILL_NAME
description: Auto-generated skill bundling an MCP server CLI generated by mcporter. (Minimal metadata only.)
---

# Assistant action required

This SKILL.md intentionally contains minimal metadata only. The assistant that executed create-skill-from-mcp-server MUST populate this SKILL.md with detailed usage instructions, examples, and safety notes in English.

See .assistant_skill_metadata.json for generation details.
SKILL_MD

# Write metadata file for the assistant
cat > "$DEST_DIR/.assistant_skill_metadata.json" <<JSON
{
  "generated_by": "create-skill-from-mcp-server",
  "mcp_command": "$MCP_COMMAND",
  "bundle": "$BUNDLE",
  "artifact": "$BASENAME",
  "destination": "$DEST_DIR/$BASENAME",
  "created_at": "$CREATED_DATE",
  "assistant_action": "populate_skill_md"
}
JSON

echo "[create-skill-from-mcp-server] Created new skill at: $DEST_DIR"

echo "[create-skill-from-mcp-server] Generated CLI file: $DEST_DIR/$BASENAME"

echo "[create-skill-from-mcp-server] Wrote placeholder SKILL.md and .assistant_skill_metadata.json - assistant must populate SKILL.md with usage in English"

echo "Done. Review $DEST_DIR and commit if desired."

exit 0
